name: Build Godot Project

on:
  push:
    branches: [ main ]
  release:
    branches: [ main ]
    types: [published]
  workflow_dispatch:

env:
  EXPORT_NAME: harmonyheroes

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 🧾 Checkout
        with:
          lfs: true
      - uses: chickensoft-games/setup-godot@v1
        name: 🤖 Setup Godot
        with:
          version: 4.0.3
          use-dotnet: false
      - name: 🦺 Build Debug Runnable
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          mkdir -v -p build/linux
          godot -v --headless --export-debug "linux" build/linux/$EXPORT_NAME.x86_64
      - name: 🦺 Build Release Runnable
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          mkdir -v -p build/linux
          godot -v --headless --export-release "linux" build/linux/$EXPORT_NAME.x86_64
      - name: 💽 Get Current Tag
        id: tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: 📦 Upload to itch.io
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: harmonyheroes
          ITCH_USER: ancocodet
          PACKAGE: build/linux
          VERSION: ${{ steps.versiontag.outputs.tag }}
      - name: 📦 Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
          
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 🧾 Checkout
        with:
          lfs: true
      - uses: chickensoft-games/setup-godot@v1
        name: 🤖 Setup Godot
        with:
          version: 4.0.3
          use-dotnet: false
      - name: 🦺 Build Debug Runnable
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          mkdir -v -p build/windows
          godot -v --headless --export-debug "windows" build/windows/$EXPORT_NAME.exe
      - name: 🦺 Build Release Runnable
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          mkdir -v -p build/windows
          godot -v --headless --export-release "windows" build/windows/$EXPORT_NAME.exe
      - name: 💽 Get Current Tag
        id: tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: 📦 Upload to itch.io
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: harmonyheroes
          ITCH_USER: ancocodet
          PACKAGE: build/windows
          VERSION: ${{ steps.versiontag.outputs.tag }}
      - name: 📦 Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
          
  build-macos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 🧾 Checkout
        with:
          lfs: true
      - uses: chickensoft-games/setup-godot@v1
        name: 🤖 Setup Godot
        with:
          version: 4.0.3
          use-dotnet: false
      - name: 🦺 Build Debug Runnable
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          mkdir -v -p build/macos
          godot -v --headless --export-debug "mac" build/macos/$EXPORT_NAME.app
      - name: 🦺 Build Release Runnable
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          mkdir -v -p build/macos
          godot -v --headless --export-release "mac" build/macos/$EXPORT_NAME.app
      - name: 💽 Get Current Tag
        id: tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: 📦 Upload to itch.io
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: osx
          ITCH_GAME: harmonyheroes
          ITCH_USER: ancocodet
          PACKAGE: build/macos
          VERSION: ${{ steps.versiontag.outputs.tag }}
      - name: 📦 Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: macos
          path: build/macos

