name: Build Godot Project

on: [ workflow_dispatch ]

env:
  GODOT_VERSION: 4.0.3
  EXPORT_NAME: harmonyheroes

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 🧾 Checkout
        with:
          lfs: true
      - uses: chickensoft-games/setup-godot@v1
        name: 🤖 Setup Godot
        with:
          version: 4.0.3
          use-dotnet: false
      - name: Build Runnable
        run: |
          mkdir -v -p build/linux
          godot -v --headless --export-debug "linux" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
          
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 🧾 Checkout
        with:
          lfs: true
      - uses: chickensoft-games/setup-godot@v1
        name: 🤖 Setup Godot
        with:
          version: 4.0.3
          use-dotnet: false
      - name: Build Runnable
        run: |
          mkdir -v -p build/windows
          godot -v --headless --export-debug "windows" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
          
  build-macos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 🧾 Checkout
        with:
          lfs: true
      - uses: chickensoft-games/setup-godot@v1
        name: 🤖 Setup Godot
        with:
          version: 4.0.3
          use-dotnet: false
      - name: Build Runnable
        run: |
          mkdir -v -p build/macos
          godot -v --headless --export-debug "macos" ../build/macos/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: macos
          path: build/macos

